/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import io.Pair;
import processing.*;
import test.RTest;
import tree.*;

import java.util.ArrayList;
import java.util.List;

/**
 * @author MY
 */
public class Compiler extends javax.swing.JFrame {
	static int i = 1;

	String _stack = "";
	String _input = "";
	String _output = "";
	String origin = "";

	/**
	 * Creates new form cuteboy
	 */
	public Compiler() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(233, 233, 233));
		setPreferredSize(new java.awt.Dimension(1300, 800));

		jPanel1.setBackground(new java.awt.Color(237, 237, 237));
		jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setFont(new java.awt.Font("微软雅黑 Light", 0, 14)); // NOI18N
		jButton1.setText("词法分析");
		jButton1.setBorder(null);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setBackground(new java.awt.Color(255, 255, 255));
		jButton2.setFont(new java.awt.Font("微软雅黑 Light", 0, 14)); // NOI18N
		jButton2.setText("语法分析");
		jButton2.setBorder(null);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		jTextArea1.setRows(5);
		jTextArea1.setBorder(null);
		jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
		jTextArea1.setSelectionColor(new java.awt.Color(153, 153, 153));
		jScrollPane1.setViewportView(jTextArea1);

		jTextArea2.setBackground(new java.awt.Color(238, 238, 238));
		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		jTextArea2.setRows(5);
		jTextArea2.setBorder(null);
		jTextArea2.setCaretColor(new java.awt.Color(227, 227, 227));
		jScrollPane2.setViewportView(jTextArea2);

		jTextArea3.setBackground(new java.awt.Color(238, 238, 238));
		jTextArea3.setColumns(20);
		jTextArea3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		jTextArea3.setRows(5);
		jTextArea3.setBorder(null);
		jTextArea3.setCaretColor(new java.awt.Color(227, 227, 227));
		jScrollPane3.setViewportView(jTextArea3);

		jTextArea4.setBackground(new java.awt.Color(238, 238, 238));
		jTextArea4.setColumns(20);
		jTextArea4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		jTextArea4.setRows(5);
		jTextArea4.setBorder(null);
		jTextArea4.setCaretColor(new java.awt.Color(227, 227, 227));
		jScrollPane4.setViewportView(jTextArea4);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(85, 85, 85)
								.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(351, 351, 351))
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane2)
										.addComponent(jScrollPane1)
										.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
										.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(36, 36, 36))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		_stack = "";
		_input = "";
		_output = "";
		i = 1;
		jTextArea2.setText("");
		jTextArea3.setText("");
		jTextArea4.setText("");
		String a = "";
		List<String> input = new ArrayList<>();

		String[] split = jTextArea1.getText().split("\n");
		for (String line : split)
			input.add(line);

		Lexer lexer = new Lexer(input);
		List<List<Pair<String, String>>> source = lexer.getOriginalCode();
		List<Pair<String, String>> codeList = lexer.getCodeList();

		for (Pair<String, String> token : codeList) {
			a += token.getFirst() + "\t[" + token.getSecond() + "]\n";
		}

		for (List<Pair<String, String>> line : source) {
			for (Pair<String, String> token : line)
				origin += token.getFirst() + " ";
			origin += "\n";
		}

		jTextArea1.setText(origin);
		jTextArea2.setText(a);
		origin = "";
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextArea2.setText("");
		jTextArea3.setText("");
		jTextArea4.setText("");
		Node n = new Node("Program");

		List<String> input = new ArrayList<>();

		String[] split = jTextArea1.getText().split("\n");
		for (String line : split)
			input.add(line);

		Lexer lexer = new Lexer(input);
		Syntax syntax = new Syntax(n,lexer);

		List<Pair<String, String>> stackInfo = syntax.getStackInfo();
		List<String> inputInfo = syntax.getInputInfo();
		List<String> outputInfo = syntax.getOutputInfo();

		if (stackInfo.get(i).getFirst() != null) {
			for (int j = 0; j < stackInfo.size(); j++)
				if (stackInfo.get(j).getFirst().equals(i + "")) {
					_stack += stackInfo.get(j).getFirst() + " " + stackInfo.get(j).getSecond() + "\n";
					_input += stackInfo.get(j).getFirst() + " " + inputInfo.get(j) + "\n";
					_output += stackInfo.get(j).getFirst() + " " + outputInfo.get(j) + "\n";
				}
		}
		i++;
		jTextArea2.setText(_stack);
		jTextArea3.setText(_input);
		jTextArea4.setText(_output);
		//Syntax.DrawTree(n);

		try {
			Runtime rt = Runtime.getRuntime();
			rt.exec("java -jar RTest.jar");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Compiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Compiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Compiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Compiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

        /* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Compiler().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	// End of variables declaration
}
